services:
  - type: web
    name: frps-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /api/status
    envVars:
      - key: FRP__SERVER__BIND_PORT
        value: "7000"
      - key: FRP__WEBSERVER__PORT
        value: "7500"
      - key: FRP__WEBSERVER__USER
        value: "admin"
      - key: FRP__AUTH__TOKEN
        generateValue: true
      - key: FRP__WEBSERVER__PASSWORD
        generateValue: true
