# services 關鍵字是所有服務定義的開始
services:
  # - 表示這是一個列表項，定義一個服務
  - type: web
    name: frps-server
    runtime: docker
    # region, plan, dockerfilePath 都是此服務的屬性
    region: oregon # 建議使用離您或您的使用者近的區域
    plan: free # 指定使用免費方案
    dockerfilePath: ./Dockerfile
    
    # 健康檢查路徑。frps 的儀表板提供了一個完美的端點
    healthCheckPath: /api/status

    # 環境變數區塊，所有縮排和格式都經過校正
    envVars:
      # --- WebSocket 核心配置 ---

      # 格式: 列表項 (-) 後，下一行縮排，包含 key 和 fromEnv
      # 作用: 讓 frps 的 vhost 監聽器使用 Render 提供的 PORT
      - key: FRP__SERVER__VHOST_HTTP_PORT
        fromEnv: PORT # 從 Render 內建的 PORT 環境變數獲取值

      # 作用: 設定 frps 的子域名主機，這是 vhost 模式所必需的
      - key: FRP__SERVER__SUBDOMAIN_HOST
        fromEnv: RENDER_EXTERNAL_HOSTNAME # 從 Render 內建的主機名變數獲取值

      # --- Web UI 與認證配置 ---

      # 作用: 讓 Web 管理介面也使用同一個 PORT，與代理服務共存
      - key: FRP__WEBSERVER__PORT
        fromEnv: PORT

      # 格式: 列表項 (-) 後，下一行縮排，包含 key 和 value
      # 作用: 設定 Web UI 的登入使用者名稱
      - key: FRP__WEBSERVER__USER
        value: "admin" # value 的值建議用引號包裹

      # 格式: 列表項 (-) 後，下一行縮排，包含 key 和 generateValue
      # 作用: 讓 Render 為 Web UI 自動生成一個安全的密碼
      - key: FRP__WEBSERVER__PASSWORD
        generateValue: true # generateValue 不能與 value 或 fromEnv 共存

      # 作用: 讓 Render 自動生成一個安全的 frp 連線權杖 (token)
      - key: FRP__AUTH__TOKEN
        generateValue: true
