services:
  - type: web
    name: frps-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheck:
      path: /api/status
      port: 7500
      initialDelaySeconds: 30
    ports:
      - port: 7500
        protocol: HTTP
      - port: 7000
        protocol: TCP
    envVars:
      - key: FRP__SERVER__BIND_PORT
        value: "7000"
      - key: FRP__WEBSERVER__PORT
        value: "7500"
      - key: FRP__WEBSERVER__USER
        value: "admin"
      - key: FRP__AUTH__TOKEN
        generateValue: true
      - key: FRP__WEBSERVER__PASSWORD
        generateValue: true
