services:
  - type: private  # <-- **重要變更：改為 private 服務**
    name: frps-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon

    # --- 端口配置：只定義核心的 TCP 端口 ---
    # private service 的核心就是 TCP 端口，所以這個定義是最直接的
    ports:
      - port: 7000
        protocol: TCP

    # --- 環境變數保持不變 ---
    # frps 仍然會在容器內部啟動 7000 (TCP) 和 7500 (Dashboard) 端口
    envVars:
      - key: FRP__SERVER__BIND_PORT
        value: "7000"
      - key: FRP__WEBSERVER__PORT
        value: "7500"
      - key: FRP__WEBSERVER__USER
        value: "admin"
      - key: FRP__AUTH__TOKEN
        generateValue: true
      - key: FRP__WEBSERVER__PASSWORD
        generateValue: true
