services:
- type: web
  name: tws-proxy-4000
  runtime: python
  protocol: tcp
  plan: starter
  region: singapore
  branch: main
  startCommand: "python proxy.py"
  envVars:
    - key: TARGET_HOST
      value: ndc1.ibllc.com
    - key: TARGET_PORT
      value: 4000
- type: web
  name: tws-proxy-4001
  runtime: python
  protocol: tcp
  plan: starter
  region: singapore
  branch: main
  startCommand: "python proxy.py"
  envVars:
    - key: TARGET_HOST
      value: ndc1.ibllc.com
    - key: TARGET_PORT
      value: 4001
