services:
  - type: web
    name: frps-server
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: FRP__SERVER__VHOST_HTTP_PORT
        fromEnv: PORT
      - key: FRP__SERVER__SUBDOMAIN_HOST
        fromEnv: RENDER_EXTERNAL_HOSTNAME
      - key: FRP__WEBSERVER__PORT
        fromEnv: PORT
      - key: FRP__WEBSERVER__USER
        value: "admin"
      - key: FRP__WEBSERVER__PASSWORD
        generateValue: true
      - key: FRP__AUTH__TOKEN
        generateValue: true
